# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='photo_table',
        ),
    ]
