# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_advertisement_photo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userFavorites',
            field=models.CommaSeparatedIntegerField(blank=True, default='', max_length=1000),
        ),
    ]
