# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160323_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Enter correct phone number', regex='/^\\+996\\d{9}$/')]),
        ),
    ]
