# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160324_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
