# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160324_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communications', models.TextField()),
                ('area', models.FloatField()),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='KidsThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'kids_things',
            },
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tourism',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('motor_power', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'transport',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='clothes_sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Housing'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='kids_things',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.KidsThings'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='tourism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tourism'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Transport'),
        ),
    ]
