# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160328_0733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='housing',
            table='housing',
        ),
    ]
