# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160328_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourism',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
