# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160328_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'ordering': ['area']},
        ),
        migrations.AlterModelOptions(
            name='kidsthings',
            options={'ordering': ['age']},
        ),
        migrations.AlterModelOptions(
            name='tourism',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
