# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 08:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160328_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(help_text='Check - for boy , None - for girl')),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='clothes_sex',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0.01)]),
        ),
        migrations.AlterField(
            model_name='housing',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0.01)]),
        ),
    ]
