# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160329_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterModelOptions(
            name='housing',
            options={'ordering': ['area'], 'verbose_name_plural': 'Housing'},
        ),
        migrations.AlterModelOptions(
            name='kidsthings',
            options={'ordering': ['age'], 'verbose_name_plural': 'Kids Things'},
        ),
        migrations.AlterModelOptions(
            name='tourism',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tourism'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name_plural': 'Transport'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Clothes'),
        ),
    ]
