# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160329_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['year'], 'verbose_name_plural': 'Transport'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sex',
            field=models.BooleanField(help_text='Check - for Male , None - for Female'),
        ),
    ]
