# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160329_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourism',
            new_name='Recreation',
        ),
        migrations.AlterModelOptions(
            name='recreation',
            options={'ordering': ['name'], 'verbose_name_plural': 'Recreation'},
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='tourism',
            new_name='recreation',
        ),
        migrations.AlterModelTable(
            name='recreation',
            table='recreation',
        ),
    ]
