# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160329_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
